### ISSUE TITLE
 Web Frontend throws exception: TemplateNotFound index.html

### ISSUE THREAD

**Issue by shon** [maxking/paper-to-git#17]
Web Frontend tracebacks with template error on accessing http://127.0.0.1:5000/

- I installed paper-to-git on my Ubuntu 18.04 system (Python 3.6.5). 
- Created a env using pipenv
- Started web frontend
- Tried accessing it from browser 

```
(paper-JfzL-Txt) [shon@laptop:~/paper] $ paper-git serve
 * Serving Flask app "papergit.server" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2018-09-18 11:35:48,605] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/shon/.local/share/virtualenvs/paper-JfzL-Txt/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shon/.local/share/virtualenvs/paper-JfzL-Txt/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shon/.local/share/virtualenvs/paper-JfzL-Txt/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shon/.local/share/virtualenvs/paper-JfzL-Txt/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/shon/.local/share/virtualenvs/paper-JfzL-Txt/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shon/.local/share/virtualenvs/paper-JfzL-Txt/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shon/.local/share/virtualenvs/paper-JfzL-Txt/lib/python3.6/site-packages/papergit/server.py", line 26, in index
    folders=PaperFolder.select())
  File "/home/shon/.local/share/virtualenvs/paper-JfzL-Txt/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/shon/.local/share/virtualenvs/paper-JfzL-Txt/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/shon/.local/share/virtualenvs/paper-JfzL-Txt/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/shon/.local/share/virtualenvs/paper-JfzL-Txt/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/shon/.local/share/virtualenvs/paper-JfzL-Txt/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/shon/.local/share/virtualenvs/paper-JfzL-Txt/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/shon/.local/share/virtualenvs/paper-JfzL-Txt/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
127.0.0.1 - - [18/Sep/2018 11:35:48] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [18/Sep/2018 11:35:48] "GET /favicon.ico HTTP/1.1" 404 -

```

**Comment by sparkslabs** [comment]
Also seeing this error (4 years later?)
Ubuntu 22.04
Python 3.10.4
Started web front end
Tried access from browser

Same error messages as previous user.

**Comment by maxking** [comment]
Can you try installing from the latest commit and see if the problem still persists?

**Comment by sparkslabs** [comment]
Will do!
